preload = /home/rdf-2041/dotfiles/.config/hypr/arch_hero_wallpaper.jpg
wallpaper {
    monitor = eDP-2
    path = /home/rdf-2041/dotfiles/.config/hypr/arch_hero_wallpaper.jpg
}

splash = false
ipc = off

