[directory]
# 📂 Полностью отключает ограничение на 3 каталога (выводить весь путь без остатка!)
truncation_length = 0

# Запрещает отсекать путь до корня текущего Git-репозитория
truncate_to_repo = false

# 🏠 Сохраняет каноничный символ тильды ~ в качестве начала домашней директории
home_symbol = "~"

# Отключает сокращение имен родительских папок до одной буквы
fish_style_pwd_dir_length = 0
